// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxrpexpbhsgbfiwclnnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cnBleHBiaHNnYmZpd2Nsbm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzYwMzgsImV4cCI6MjA2NTUxMjAzOH0.0JhJATRxJ9qGRUCiIKY9nIz4HxF-7fwUAtSMfBNOhnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);